# Generated by Django 3.0.7 on 2020-06-15 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(default='Other Category', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_Title', models.CharField(default='None', max_length=200)),
                ('product_name', models.CharField(default='Product Name Missing', max_length=200)),
                ('condition', models.CharField(default='Not Mentioned', max_length=200)),
                ('brand_Type', models.CharField(default='Not Mentioned', max_length=200)),
                ('model_of_product', models.CharField(default='Not Mentioned', max_length=200)),
                ('price_of_product', models.FloatField(default='Not on Sale')),
                ('add_description', models.CharField(default='Not Mentioned', max_length=200)),
                ('upload_photos', models.ImageField(default='No Images', upload_to='images/')),
                ('active_status', models.BooleanField(default=True)),
                ('time_of_post', models.DateField(default='')),
                ('category_of_product', models.ForeignKey(default='Other Category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_product', to='advertisments.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdd',
            fields=[
                ('user_name', models.CharField(default='Unknown', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('registeradd_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='advertisments.RegisterAdd')),
                ('add_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
            bases=('advertisments.registeradd',),
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('sub_category_name', models.CharField(default='Others', max_length=200, primary_key=True, serialize=False)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisments.Category')),
            ],
        ),
        migrations.AddField(
            model_name='registeradd',
            name='owner',
            field=models.ForeignKey(default='Unknown', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='advertisments.UserAdd'),
        ),
        migrations.AddField(
            model_name='registeradd',
            name='sub_category_of_product',
            field=models.ForeignKey(default='Others', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_product', to='advertisments.sub_category'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_customer', models.CharField(default='Identity Not mentioned', max_length=200)),
                ('reviews_of_add', models.CharField(default='None', max_length=500)),
                ('time_of_review', models.DateField(default='')),
                ('review_of_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisments.Products')),
            ],
        ),
    ]
